"""Prototype UI copy, separate from unmodified Waha curriculum questions."""
EN = {
    "welcome": "Welcome to a new session of Discovering God! Let's begin by catching up on how we're doing. First, can you say your name so I can recognize who is who? Then, based on what's happened to you since last time we met, what is something that you're thankful for?",
    "text_notice": 'This is a text rehearsal, not voice enrollment. Introduce one person per message. After each name is confirmed, say: William, everyone is here.',
    "confirm_name": 'I heard {name}. Is that your name? Please answer yes or no yourself.',
    "same_speaker": 'Please let the person who just introduced themselves confirm their own name, one at a time.',
    "next_person": 'Thank you. Who is next? Please say your name and something you are thankful for since we last met. When everyone has shared, say: William, everyone is here.',
    "retry_intro": 'Please say your name and something you are thankful for since we last met, one person at a time.',
    "solo_intro": 'I heard more than one speaker. Please repeat the introduction one person at a time.',
    "more_speech": 'Please start with your name and tell us a little more about what you are thankful for so I can recognize your voice.',
    "speaker_collision": 'This voice has the same temporary label as someone already introduced. Please repeat your own name and a longer introduction; I will not merge the two people.',
    "duplicate_name": 'That name is already on the list. If you are a different person, please use a distinct name, such as your first and last name.',
    "full": 'The configured limit is {count} participants. Please finish enrollment or stop and change the limit.',
    "roster": 'I have {count} participants: {names}. Is this the complete and correct group? Please say yes or no.',
    "retry_roster": 'Let us start the introductions again so the names are correct. Please introduce yourselves one at a time.',
    "facilitation_rules": 'I will ask the questions, not answer them. Let us find answers in the passage together. Everyone is welcome to share or pass. Say William, next question when the group is ready; I will check before moving on. You can also ask me to repeat, read the passage again, pause, resume, or stop.',
    "redirect": 'What does the passage say? Where do you find that in the story? Let us hear what the group notices.',
    "invite": 'Would anyone else like to share? Take your time. Tell me when the group is ready for the next question.',
    "confirm_next": 'Is everyone ready to move on? Please say yes, or no if you would like more time.',
    "confirm_next_missing": 'I have not yet heard from {names} on this question. Would you like to share or pass? Is the group ready to move on?',
    "paused": 'Paused. Say William, resume when you are ready.',
    "resumed": 'We can continue. Take your time, or ask me to repeat the current question.',
    "stopped": 'The session has stopped. Session-only voice identifiers and names have been cleared.',
    "done": 'Our session is complete. Thank you for discovering together.',
    "manual_scripture": 'Please have someone read Genesis chapter one, verses one through twenty-five from NVI. Tell me when the group is ready to continue.',
    "error": 'I could not process that reliably. Please repeat; we have not moved to the next question.',
    "safety": 'Let us pause. If someone is in immediate danger, contact local emergency services and a trusted person nearby. Please prioritize getting to safety.',
}

ES = {
    "welcome": '¡Bienvenidos a una nueva sesión de Descubriendo a Dios! Comencemos poniéndonos al día sobre cómo estamos. Primero, ¿puedes decir tu nombre para que pueda reconocer quién es quién? Luego, pensando en lo que te ha pasado desde la última vez que nos reunimos, ¿por qué estás agradecido?',
    "text_notice": 'Este es un ensayo por texto, no una inscripción de voces. Presenten a una persona por mensaje. Después de confirmar los nombres, digan: William, ya estamos todos.',
    "confirm_name": 'Escuché {name}. ¿Ese es tu nombre? Por favor, responde tú mismo sí o no.',
    "same_speaker": 'Por favor, dejemos que la persona que acaba de presentarse confirme su propio nombre, de uno en uno.',
    "next_person": 'Gracias. ¿Quién sigue? Por favor, di tu nombre y algo por lo que estás agradecido desde la última vez que nos reunimos. Cuando todos hayan compartido, digan: William, ya estamos todos.',
    "retry_intro": 'Por favor, di tu nombre y algo por lo que estás agradecido desde la última vez que nos reunimos, una persona a la vez.',
    "solo_intro": 'Escuché más de una voz. Por favor, repitan la presentación de uno en uno.',
    "more_speech": 'Por favor, comienza con tu nombre y cuéntanos un poco más sobre aquello por lo que estás agradecido para que pueda reconocer tu voz.',
    "speaker_collision": 'Esta voz tiene la misma etiqueta temporal que otra persona. Repite tu nombre y una presentación más larga; no voy a combinar a dos personas.',
    "duplicate_name": 'Ese nombre ya está en la lista. Si eres otra persona, usa un nombre distinto, por ejemplo, tu nombre y apellido.',
    "full": 'El límite configurado es de {count} participantes. Terminen la inscripción o detengan la sesión para cambiar el límite.',
    "roster": 'Tengo {count} participantes: {names}. ¿Este es el grupo completo y correcto? Digan sí o no.',
    "retry_roster": 'Volvamos a comenzar las presentaciones para registrar bien los nombres. Preséntense de uno en uno.',
    "facilitation_rules": 'Haré las preguntas, pero no las responderé. Busquemos las respuestas juntos en el pasaje. Todos pueden compartir o pasar. Digan William, siguiente pregunta cuando el grupo esté listo; confirmaré antes de avanzar. También pueden pedirme repetir, leer el pasaje otra vez, pausar, continuar o detener la sesión.',
    "redirect": '¿Qué dice el pasaje? ¿Dónde encuentran eso en la historia? Escuchemos lo que observa el grupo.',
    "invite": '¿Alguien más quiere compartir? Tómense su tiempo. Díganme cuando el grupo esté listo para la siguiente pregunta.',
    "confirm_next": '¿Todos están listos para continuar? Digan sí, o no si necesitan más tiempo.',
    "confirm_next_missing": 'Todavía no he escuchado a {names} sobre esta pregunta. ¿Quieren compartir o pasar? ¿El grupo está listo para continuar?',
    "paused": 'En pausa. Digan William, continúa cuando estén listos.',
    "resumed": 'Podemos continuar. Tómense su tiempo o pídanme repetir la pregunta actual.',
    "stopped": 'La sesión se ha detenido. Se han borrado los nombres y los identificadores de voz de esta sesión.',
    "done": 'Terminamos la sesión. Gracias por descubrir juntos.',
    "manual_scripture": 'Por favor, que alguien lea Génesis, capítulo uno, versículos uno al veinticinco, en la NVI. Díganme cuando el grupo esté listo para continuar.',
    "error": 'No pude procesar eso con seguridad. Por favor, repítanlo; no hemos avanzado a la siguiente pregunta.',
    "safety": 'Hagamos una pausa. Si alguien está en peligro inmediato, contacten a los servicios de emergencia locales y a una persona de confianza cercana. Lo primero es ponerse a salvo.',
}
